#!/bin/bash
# TWRP Porting Tool - Auto Config Generator
# Generate config files otomatis dari device info

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORK_DIR="${SCRIPT_DIR}/../work"
CONFIG_DIR="${WORK_DIR}/config"
EXTRACTED="${WORK_DIR}/extracted"

echo "============================================"
echo "  TWRP Porting Tool - AUTO CONFIG"
echo "============================================"
echo ""

# Check ADB
if ! command -v adb &> /dev/null; then
    echo "[ERROR] ADB tidak ditemukan!"
    exit 1
fi

# Check device
DEVICE=$(adb devices | grep -w "device" | head -1 | awk '{print $1}')
if [ -z "$DEVICE" ]; then
    echo "[ERROR] Tidak ada perangkat terhubung!"
    exit 1
fi

# Get root
ROOT=$(adb shell su -c "whoami" 2>/dev/null | tr -d '\r')
if [ "$ROOT" != "root" ]; then
    echo "[ERROR] Root access tidak tersedia!"
    exit 1
fi
echo "[OK] Perangkat: $DEVICE"
echo "[OK] Root access tersedia"
echo ""

# Get device info
echo "[1/6] Mengambil informasi device..."
BRAND=$(adb shell getprop ro.product.brand 2>/dev/null | tr -d '\r')
MODEL=$(adb shell getprop ro.product.model 2>/dev/null | tr -d '\r')
DEVICE_NAME=$(adb shell getprop ro.product.device 2>/dev/null | tr -d '\r')
HARDWARE=$(adb shell getprop ro.boot.hardware 2>/dev/null | tr -d '\r')
ANDROID=$(adb shell getprop ro.build.version.release 2>/dev/null | tr -d '\r')
SDK=$(adb shell getprop ro.build.version.sdk 2>/dev/null | tr -d '\r')
SLOT=$(adb shell getprop ro.boot.slot_suffix 2>/dev/null | tr -d '\r')
SERIAL=$(adb shell getprop ro.serialno 2>/dev/null | tr -d '\r')
BOOTIMAGE=$(adb shell getprop ro.bootimage.build.fingerprint 2>/dev/null | tr -d '\r')

# Detect SoC
SOC=$(adb shell getprop ro.hardware 2>/dev/null | tr -d '\r')
if [ -z "$SOC" ]; then
    SOC="$HARDWARE"
fi

# Detect architecture
ARCH=$(adb shell getprop ro.product.cpu.abi 2>/dev/null | tr -d '\r')

echo "    Brand: $BRAND"
echo "    Model: $MODEL"
echo "    Device: $DEVICE_NAME"
echo "    Hardware: $HARDWARE"
echo "    Android: $ANDROID"
echo "    SDK: $SDK"
echo "    Slot: $SLOT"
echo "    Architecture: $ARCH"
echo ""

# Create config directory
mkdir -p "$CONFIG_DIR"

# 2. Generate BoardConfig.mk
echo "[2/6] Generating BoardConfig.mk..."
cat > "$CONFIG_DIR/BoardConfig.mk" << EOF
# BoardConfig.mk for $BRAND $MODEL ($DEVICE_NAME)
# Generated by TWRP Porting Tool

# Device
DEVICE_NAME := $DEVICE_NAME
PRODUCT_NAME := ${MODEL}
BOARD_NAME := ${DEVICE_NAME}

# Architecture
TARGET_ARCH := $(echo $ARCH | sed 's/arm64.*/arm64/' | sed 's/arm.*/arm/')
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := $ARCH
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

# Kernel
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_KERNEL := device/$BRAND/$DEVICE_NAME/prebuilt/kernel
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x02000000
BOARD_TAGS_OFFSET := 0x00000100

# Boot Image
BOARD_BOOT_HEADER_VERSION := 4
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 104857600

# Has DTB
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBOIMAGE := device/$BRAND/$DEVICE_NAME/prebuilt/dtbo.img

# Partitions
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 8388608000
BOARD_SUPER_PARTITION_GROUPS := qti_dynamic_partitions
BOARD_QTI_DYNAMIC_PARTITIONS_SIZE := 8388545792
BOARD_QTI_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm system_ext

# Filesystem
TARGET_USERDATA_USE_F2FS := true
BOARD_USES_SYSTEMIMAGE_EXTIMAGE := true
BOARD_USES_VENDORIMAGE_EXTIMAGE := true

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_ROLLBACK_INDEX := 0

# SELinux
BOARD_SEPOLICY_DIRS += device/$BRAND/$DEVICE_NAME/sepolicy

# TWRP specific
TW_THEME := portrait_hdpi
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE_METADATA_CRYPT := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_REBOOT_BOOTLOADER := false
TW_NO_REBOOT_RECOVERY := false
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_NTFS_3G := true
TW_USE_MODEL_DEVICE_ID := true
TW_DEFAULT_LANGUAGE := en

# USB
BOARD_USB_CONFIG := adb
EOF

echo "    [OK] BoardConfig.mk generated"

# 3. Generate device.mk
echo "[3/6] Generating device.mk..."
cat > "$CONFIG_DIR/device.mk" << EOF
# device.mk for $BRAND $MODEL ($DEVICE_NAME)
# Generated by TWRP Porting Tool

\$(call inherit-product, \$(SRC_TARGET_DIR)/product/languages_full.mk)

# Device identifier
PRODUCT_DEVICE := $DEVICE_NAME
PRODUCT_NAME := ${MODEL}_twrp
PRODUCT_BRAND := $BRAND
PRODUCT_MODEL := $MODEL
PRODUCT_MANUFACTURER := $BRAND

# Overlay
DEVICE_PACKAGE_OVERLAYS += device/$BRAND/$DEVICE_NAME/overlay

# Recovery
PRODUCT_COPY_FILES += device/$BRAND/$DEVICE_NAME/recovery.fstab:recovery/etc/fstab.$DEVICE_NAME

# Boot animation
PRODUCT_COPY_FILES += device/$BRAND/$DEVICE_NAME/bootanimation.zip:system/media/bootanimation.zip

# TWRP
PRODUCT_PACKAGES += \\
    twrp \\
    busybox \\
    toolbox

# Inherit from device config
\$(call inherit-product, device/$BRAND/$DEVICE_NAME/device.mk)
EOF

echo "    [OK] device.mk generated"

# 4. Generate recovery.fstab
echo "[4/6] Generating recovery.fstab..."
FSTAB_SRC=$(find "$EXTRACTED/vendor_boot/ramdisk" -name "fstab.*" 2>/dev/null | head -1)

if [ -n "$FSTAB_SRC" ]; then
    cp "$FSTAB_SRC" "$CONFIG_DIR/recovery.fstab"
    
    # Add TWRP specific entries
    cat >> "$CONFIG_DIR/recovery.fstab" << 'EOF'

# TWRP additions
/dev/block/by-name/userdata /userdata ext4 ro,nodev,noatime,nosuid wait,check
/dev/block/by-name/cache /cache ext4 ro,nodev,noatime,nosuid wait,check
/dev/block/by-name/metadata /metadata f2fs nodev,noatime,nosuid wait,formattable,check
EOF
    echo "    [OK] recovery.fstab generated from device fstab"
else
    # Create template
    cat > "$CONFIG_DIR/recovery.fstab" << EOF
# recovery.fstab for $BRAND $MODEL ($DEVICE_NAME)
# Generated by TWRP Porting Tool
# NOTE: Edit this file according to your device partition layout

# System
/dev/block/by-name/system /system erofs ro wait,avb=vbmeta_system,logical,first_stage_mount,slotselect

# Vendor
/dev/block/by-name/vendor /vendor erofs ro wait,avb=vbmeta_vendor,logical,first_stage_mount,slotselect

# Product
/dev/block/by-name/product /product erofs ro wait,avb=vbmeta_product,logical,first_stage_mount,slotselect

# ODM
/dev/block/by-name/odm /odm erofs ro wait,avb=vbmeta_odm,logical,first_stage_mount,slotselect

# System_ext
/dev/block/by-name/system_ext /system_ext erofs ro wait,avb=vbmeta_system,logical,first_stage_mount,slotselect

# Metadata
/dev/block/by-name/metadata /metadata f2fs nodev,noatime,nosuid wait,formattable,first_stage_mount,check

# Userdata
/dev/block/by-name/userdata /userdata ext4 ro,nodev,noatime,nosuid wait,check

# Cache
/dev/block/by-name/cache /cache ext4 ro,nodev,noatime,nosuid wait,check
EOF
    echo "    [WARN] Fstab source tidak ditemukan, template dibuat"
fi

# 5. Generate device tree structure
echo "[5/6] Generating device tree structure..."
DT_DIR="$CONFIG_DIR/device_tree"
mkdir -p "$DT_DIR"/{sepolicy,overlay,prebuilt}

# Copy kernel
cp "$EXTRACTED/boot/kernel" "$DT_DIR/prebuilt/" 2>/dev/null || true
cp "$EXTRACTED/boot/dtb" "$DT_DIR/prebuilt/" 2>/dev/null || true

# Copy fstab
cp "$CONFIG_DIR/recovery.fstab" "$DT_DIR/"

# Copy init.recovery.rc
cp "$EXTRACTED/vendor_boot/init.recovery.common.rc" "$DT_DIR/" 2>/dev/null || true

# Create AndroidProducts.mk
cat > "$DT_DIR/AndroidProducts.mk" << EOF
PRODUCT_NAME := ${MODEL}_twrp
PRODUCT_DEVICE := $DEVICE_NAME
PRODUCT_BRAND := $BRAND
PRODUCT_MODEL := $MODEL
PRODUCT_MANUFACTURER := $BRAND

COMMON_LUNCH_CHOICES := \\
    ${MODEL}_twrp-eng
EOF

# Create .repo manifest
cat > "$DT_DIR/README.md" << EOF
# TWRP Device Tree for $BRAND $MODEL ($DEVICE_NAME)

## Generated by TWRP Porting Tool

### Files

| File | Description |
|------|-------------|
| BoardConfig.mk | Board configuration |
| device.mk | Device makefile |
| recovery.fstab | Recovery fstab |
| prebuilt/kernel | Prebuilt kernel |
| prebuilt/dtb | Device tree blob |
| sepolicy/ | SELinux policies |
| overlay/ | Runtime resource overlay |

### Build TWRP

\`\`\`bash
# Setup build environment
source build/envsetup.sh
lunch ${MODEL}_twrp-eng

# Build TWRP
mka recoveryimage
\`\`\`

### Flash

\`\`\`bash
adb reboot bootloader
fastboot flash boot out/target/product/$DEVICE_NAME/recovery.img
fastboot reboot recovery
\`\`\`

### Notes

- Kernel version: Check prebuilt/kernel
- SoC: $SOC
- Architecture: $ARCH
- Android: $ANDROID (SDK $SDK)
EOF

echo "    [OK] Device tree structure generated"

# 6. Generate summary
echo "[6/6] Generating config summary..."
cat > "$CONFIG_DIR/SUMMARY.md" << EOF
# Auto-Generated Config Summary

## Device Info

| Field | Value |
|-------|-------|
| Brand | $BRAND |
| Model | $MODEL |
| Device | $DEVICE_NAME |
| Hardware | $HARDWARE |
| Android | $ANDROID |
| SDK | $SDK |
| Architecture | $ARCH |
| Slot | $SLOT |

## Generated Files

| File | Location |
|------|----------|
| BoardConfig.mk | $CONFIG_DIR/BoardConfig.mk |
| device.mk | $CONFIG_DIR/device.mk |
| recovery.fstab | $CONFIG_DIR/recovery.fstab |
| Device Tree | $CONFIG_DIR/device_tree/ |

## Next Steps

1. Review generated configs
2. Adjust BoardConfig.mk if needed
3. Edit recovery.fstab for your device
4. Set up Android build environment
5. Build TWRP

## Build Commands

\`\`\`bash
# Setup environment
cd /path/to/android/source
source build/envsetup.sh
lunch ${MODEL}_twrp-eng

# Build
mka recoveryimage

# Output
out/target/product/$DEVICE_NAME/recovery.img
\`\`\`
EOF

echo "    [OK] Summary generated"

echo ""
echo "============================================"
echo "  AUTO CONFIG SELESAI!"
echo "============================================"
echo ""
echo "Generated files:"
echo "  $CONFIG_DIR/"
echo ""
ls -la "$CONFIG_DIR/"
echo ""
echo "Device tree:"
echo "  $CONFIG_DIR/device_tree/"
echo ""
ls -la "$CONFIG_DIR/device_tree/"
